import { ComplianceReport } from './dataService';

export const mockReports: ComplianceReport[] = [
  {
    id: '1',
    teamId: 'team-1',
    teamName: 'Team Alpha',
    feederPointId: 'fp-1',
    feederPointName: 'Feeder Point 1',
    title: 'Waste overflow at Feeder Point 1',
    description: 'The waste at Feeder Point 1 is overflowing and needs to be collected immediately.',
    status: 'pending',
    priority: 'high',
    submittedAt: new Date().toISOString(),
    submittedBy: 'John Doe',
    attachments: [
      {
        id: 'att-1',
        type: 'photo',
        url: 'https://via.placeholder.com/150',
        filename: 'report-1.jpg',
        uploadedDate: new Date().toISOString(),
      },
    ],
    submittedLocation: {
      latitude: 12.9716,
      longitude: 77.5946,
      address: 'Bangalore, India',
    },
    userId: 'user-1',
    userName: 'John Doe',
    distanceFromFeederPoint: 100,
    answers: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    tripNumber: 1,
    tripDate: '2025-09-20',
    dailyTripId: 'user-1_fp-1_2025-09-20',
  },
  {
    id: '2',
    teamId: 'team-2',
    teamName: 'Team Bravo',
    feederPointId: 'fp-2',
    feederPointName: 'Feeder Point 2',
    title: 'Scheduled maintenance at Feeder Point 2',
    description: 'Scheduled maintenance at Feeder Point 2 has been completed successfully.',
    status: 'approved',
    priority: 'medium',
    submittedAt: new Date().toISOString(),
    submittedBy: 'Jane Smith',
    attachments: [],
    submittedLocation: {
      latitude: 12.9716,
      longitude: 77.5946,
      address: 'Bangalore, India',
    },
    userId: 'user-2',
    userName: 'Jane Smith',
    distanceFromFeederPoint: 50,
    answers: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    tripNumber: 2,
    tripDate: '2025-09-20',
    dailyTripId: 'user-2_fp-2_2025-09-20',
  },
];
